apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dados
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
  spec:
    replicas: 6
    selector:
      matchLabes:
        app: php
    template:
      metadata:
        labels:
          app: php
      spec:
        containers:
        - name: php
          image: renatorp93/projeto-backend:1.0
          imagePullPolicy: Always
          ports:
          - containerPort: 80